# Generated by Django 2.0.5 on 2018-08-14 02:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 2, 13, 51, 269869, tzinfo=utc)),
        ),
    ]
